### ISSUE TITLE
Validating responses even with validate_responses = False?

### ISSUE THREAD

**Issue by lcofre** [Yelp/bravado#313]
Hi!

I am testing the cases where my api should return an error response code, so I send a request that will fail. I configured bravado to not validate the responses:
```
api = SwaggerClient.from_url('path/to/swagger.yaml', config=config = {'also_return_response': True, 'validate_responses': False, 'use_models': False})
```

But anyway I receive the error:
```
http_response = <bravado.requests_client.RequestsResponseAdapter object at 0x7fbf9bac9cf8>

    def raise_on_expected(http_response):
        """Raise an HTTPError if the response is non-2XX and matches a response
        in the swagger spec.
    
        :param http_response: :class:`bravado_core.response.IncomingResponse`
        :raises: HTTPError
        """
        if not 200 <= http_response.status_code < 300:
            raise make_http_exception(
                response=http_response,
>               swagger_result=http_response.swagger_result)
E           bravado.exception.HTTPBadRequest: 400 Bad Request: {'message': 'Error message'}

env3.5/lib/python3.5/site-packages/bravado/http_future.py:154: HTTPBadRequest
```

Thanks for your help!

**Comment by macisamuele** [comment]
This is caused by [``HttpFuture.result``](https://github.com/Yelp/bravado/blob/b6c381dbc771394d5ef7603ea1d369d78918ca62/bravado/http_future.py#L85).
Every time bravado receives an HTTP status code that is not 2xx it will raise a well defined exception (subclass of [``HTTPError``](https://github.com/Yelp/bravado/blob/v9.1.0/bravado/exception.py#L28)). The raised exception will have ``response`` attribute that will contain your response.
Note that disabling response validation does not prevent this behaviour, it just prevent to check the response body against the swagger specs.

**Comment by lcofre** [comment]
Great. Thanks very much for the explanation @macisamuele!

Now in my case, as the project is for testing my API, the 4xx responses are the expected code for some tests.

Is there any way to avoid raising this exception?

**Comment by macisamuele** [comment]
Nope ... but you cat ``try...except`` the call.
If you can post a small snippet of the test that you're writing maybe I could give some way to work it around.

**Comment by lcofre** [comment]
Thanks for the advise! I will wrap the query in try except. I post the code just in case
Sorry I can't access my tests right now, but is something like this:

```
@pytest.mark.parametrize("test_name, user_name", [
    ('200_action1', 'Tester_1'),
    ('400_action1', 'Tester_2'),
    ('200_action2', 'Tester_2'),
    ('401_action2', 'Tester_1')
])
def test_get_devices(bravado, test_name, user_name):
    # Get payload from files, user token and resource id. bravado is a fixture
    resource, response = bravado.resource.patch_resource_id(id=resource_id, resourceProperties=payload,token=user_token).result()
    
    assert compare.dictionaries(expected_output_dict, r={'status': response.status_code, 'body': resource}, debug=False)
```

On the other hand,
Do you think it would be a good enhancement for bravado to make this configurable, to not raise an exception if indicated in the initial configuration maybe? Or it deviates from the purpose of the project?

Thanks again for your help!

**Comment by macisamuele** [comment]
I think that raising a python exception in case of not 200 responses is reasonable since those type of responses means errors. Adding a config parameter could be a solution but it will open us to maintain a bigger number of different flows, so I would say that we should not change it. Obviously if a community will require that we might start thinking about it.

About your test case I'm making the following assumptions
 - ``bravado`` is a fixture that gives you a ``bravado.client.SwaggerClient`` object
 - ``bravado`` is configured with ``also_return_response``
 - is defined an endpoint that will be retrieved via ``bravado.resource.patch_resource_id```
 - a running service will respond to the requests
what are ``resource_id``, ``payload`` and ``user_token``? I'm assuming again that are somehow valid python variables that will be valid according to the swagger specs

Said so the easiest approach that I have in mind is to do something like
```python
@pytest.mark.parametrize("test_name, user_name", [
    ('200_action1', 'Tester_1'),
    ('400_action1', 'Tester_2'),
    ('200_action2', 'Tester_2'),
    ('401_action2', 'Tester_1')
])
def test_get_devices(bravado, test_name, user_name):
    raised_exception = None
    response = None
    try:
        # Get payload from files, user token and resource id. bravado is a fixture
        resource, response = bravado.resource.patch_resource_id(id=resource_id, resourceProperties=payload,token=user_token).result()
    except bravado.exceptionHttpError as e:
        raised_exception = e
    if test_name.startswith('200_'):
        assert raised_exception is None
    else:
        assert raised_exception is not None
        response = raised_exception.response
    
    assert response.status_code == int(test_name.split('_')[0])
    assert json.loads(response.text) == expected_body
```
Note I never tested the code ... so it could not work ... but I hope you get the idea :D

**Comment by lcofre** [comment]
A pity that raising the exception won't be configurable, although I understand the reasons behind.

I'll definitively follow your advice regarding catching exception and timeout. All your assumptions were correct. :)

Thanks very much!
