### ISSUE TITLE
list_models to match get_models, maybe list_resources too

### ISSUE THREAD

**Issue by bdowling** [Yelp/bravado#349]
Curious if others think it makes sense that there should be a `list_models` to correspond to `get_models` so that an implementation can easily enumerate them.  While you could reach into `client.swagger_spec.definitions`, that feels a little like it is reaching too far with get_models hiding the implementation details.  As I was implementing this I also considered a `list_resources`, but then I realized that `__dir__` was overridden to return the same.  That might still make sense for feel of consistency?

 e.g.:

```diff
--- a/bravado/client.py
+++ b/bravado/client.py
@@ -133,6 +133,12 @@ class SwaggerClient(object):
     def get_model(self, model_name):
         return self.swagger_spec.definitions[model_name]

+    def list_models(self):
+        return self.swagger_spec.definitions.keys()
+
+    def list_resources(self):
+        return self.swagger_spec.resources.keys()
+
     def _get_resource(self, item):
         """
         :param item: name of the resource to return
```

**Comment by bdowling** [comment]
Any thoughts?  Also curious why `_get_resource` is semi-private with the leading underscore...

**Comment by sjaensch** [comment]
I don't think accessing the swagger spec for getting to models and resources is a problem. Typically you don't need those, and if you do you probably should be comfortable working with the spec object.

Since SwaggerClient dynamically adds attributes to itself, using a leading underscore for non-dynamic ones makes sense to avoid name clashes. So _get_resource is not private. Due to backwards compatibility reasons, we cannot remove the older ones that don't have a leading underscore.
